# Generated by Django 4.0.1 on 2022-01-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50, unique=True)),
                ('dt_record', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('dt_record', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_cheque', models.CharField(max_length=50)),
                ('nr_conta', models.CharField(max_length=50)),
                ('dt_record', models.DateField()),
                ('dt_futura', models.DateField()),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('cd_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.empresa')),
            ],
        ),
    ]
