# Generated by Django 4.0.1 on 2022-01-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_banco_delete_user_rename_cd_empresa_cheque_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.banco'),
        ),
    ]
