# Generated by Django 4.0.1 on 2022-01-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_alter_cheque_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
