# Generated by Django 4.0.1 on 2022-01-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_cheque_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='conta',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
