# Generated by Django 4.0.1 on 2022-01-28 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_cheque_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.banco'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='conta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='dt_futura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='dt_record',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.empresa'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='nr_cheque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='nr_conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
