# Generated by Django 4.0.1 on 2022-01-28 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_alter_cheque_agencia_alter_cheque_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='banco',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='cheques.banco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheque',
            name='empresa',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='cheques.empresa'),
            preserve_default=False,
        ),
    ]
