# Generated by Django 4.0.1 on 2022-01-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_alter_cheque_banco_alter_cheque_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.banco'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.empresa'),
        ),
    ]
