# Generated by Django 4.0.1 on 2022-01-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_alter_cheque_banco_alter_cheque_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_cheque', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_conta', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_record', models.DateField(blank=True, null=True)),
                ('dt_futura', models.DateField(blank=True, null=True)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('destinatario', models.CharField(max_length=50, null=True)),
                ('valor', models.FloatField(null=True)),
                ('conta', models.CharField(blank=True, max_length=10, null=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.banco')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.empresa')),
            ],
        ),
    ]
