# Generated by Django 4.0.1 on 2022-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0009_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='dt_comp_excl',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banco',
            name='dt_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='dt_futura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='dt_record',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dt_record',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_futura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_record',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
