# Generated by Django 4.0.1 on 2022-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_historico_dt_comp_excl_alter_banco_dt_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='dt_futura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_futura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
