# Generated by Django 4.0.1 on 2022-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0011_alter_cheque_dt_futura_alter_historico_dt_futura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='dt_record',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='dt_record',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dt_record',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_comp_excl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dt_record',
            field=models.DateField(blank=True, null=True),
        ),
    ]
