# Generated by Django 4.0.1 on 2022-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0013_alter_historico_dt_comp_excl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='dt_comp_excl',
            field=models.DateField(blank=True, null=True),
        ),
    ]
