# Generated by Django 4.0.1 on 2022-01-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0014_alter_historico_dt_comp_excl'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='compensado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
