# Generated by Django 4.0.1 on 2022-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0015_historico_compensado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='nr_conta',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='nr_conta',
        ),
        migrations.AddField(
            model_name='empresa',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
    ]
