# Generated by Django 4.0.1 on 2022-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0016_remove_cheque_agencia_remove_cheque_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='conta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
