# Generated by Django 4.0.1 on 2022-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0018_cheque_user_empresa_user_historico_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cpfpj',
            field=models.CharField(max_length=50),
        ),
    ]
